// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyFactory.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MyFactory.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MyFactory.Domain.Entities.Finance.CashAdvanceEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateOnly?>("ClosedAt")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("IssueDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "IssueDate");

                    b.ToTable("CASH_ADVANCES", (string)null);
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Finance.CashAdvanceExpenseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("CashAdvanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly>("ExpenseDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CashAdvanceId", "ExpenseDate");

                    b.ToTable("CASH_ADVANCE_EXPENSES", (string)null);
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Finance.CashAdvanceReturnEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("CashAdvanceId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly>("ReturnDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("CashAdvanceId", "ReturnDate");

                    b.ToTable("CASH_ADVANCE_RETURNS", (string)null);
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Finance.ExpenseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly>("ExpenseDate")
                        .HasColumnType("date");

                    b.Property<Guid>("ExpenseTypeId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ExpenseDate");

                    b.ToTable("EXPENSES", (string)null);
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Finance.ExpenseTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("EXPENSE_TYPES", (string)null);
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Finance.MonthlyFinancialReportEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<decimal>("MaterialExpenses")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("OtherExpenses")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PayrollExpenses")
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ReportMonth")
                        .HasColumnType("integer");

                    b.Property<int>("ReportYear")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalRevenue")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ReportYear", "ReportMonth")
                        .IsUnique();

                    b.ToTable("MONTHLY_FINANCIAL_REPORTS", (string)null);
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Finance.PayrollAccrualEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("AccrualDate")
                        .HasColumnType("date");

                    b.Property<string>("AdjustmentReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("BaseAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("HoursWorked")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("PremiumAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("QtyExtra")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("QtyPlanned")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("QtyProduced")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "AccrualDate");

                    b.ToTable("PAYROLL_ACCRUALS", (string)null);
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Finance.PayrollPaymentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("PaymentDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "PaymentDate");

                    b.ToTable("PAYROLL_PAYMENTS", (string)null);
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Finance.PayrollRuleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateOnly>("EffectiveFrom")
                        .HasColumnType("date");

                    b.Property<decimal>("PremiumPercent")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("EffectiveFrom")
                        .IsUnique();

                    b.ToTable("PAYROLL_RULES", (string)null);
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Finance.TimesheetEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("HoursWorked")
                        .HasColumnType("numeric");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("WorkDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("EmployeeId", "WorkDate")
                        .IsUnique();

                    b.ToTable("TIMESHEETS", (string)null);
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Inventory.FinishedGoodsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductionOrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Qty")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductionOrderId");

                    b.HasIndex("WarehouseId");

                    b.HasIndex("ProductId", "WarehouseId", "ProductionOrderId");

                    b.ToTable("FINISHED_GOODS", (string)null);
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Inventory.FinishedGoodsMovementEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("FromWarehouseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("MovementDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ToWarehouseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("ToWarehouseId");

                    b.HasIndex("FromWarehouseId", "ToWarehouseId", "MovementDate");

                    b.ToTable("FINISHED_GOODS_MOVEMENTS", (string)null);
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Inventory.FinishedGoodsMovementItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MovementId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Qty")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MovementId");

                    b.HasIndex("ProductId");

                    b.ToTable("FINISHED_GOODS_MOVEMENT_ITEMS", (string)null);
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Inventory.FinishedGoodsStockEntity", b =>
                {
                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<int>("Qty")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("WarehouseId", "ProductId");

                    b.HasIndex("ProductId");

                    b.ToTable("FINISHED_GOODS_STOCK", (string)null);
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Inventory.InventoryMovementEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("FromWarehouseId")
                        .HasColumnType("uuid");

                    b.Property<int>("MovementType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("ProductionOrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ToDepartmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ToWarehouseId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("FromWarehouseId");

                    b.HasIndex("ProductionOrderId");

                    b.HasIndex("ToDepartmentId");

                    b.HasIndex("ToWarehouseId");

                    b.ToTable("INVENTORY_MOVEMENTS", (string)null);
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Inventory.InventoryMovementItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MovementId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Qty")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("UnitCost")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("MovementId");

                    b.ToTable("INVENTORY_MOVEMENT_ITEMS", (string)null);
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Inventory.WarehouseEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("WAREHOUSES", (string)null);
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Inventory.WarehouseMaterialEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Qty")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("WarehouseId", "MaterialId")
                        .IsUnique();

                    b.ToTable("WAREHOUSE_MATERIALS", (string)null);
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Inventory.WarehouseProductEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Qty")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("WarehouseId", "ProductId")
                        .IsUnique();

                    b.ToTable("WAREHOUSE_PRODUCTS", (string)null);
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Materials.MaterialEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MaterialTypeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UnitId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MaterialTypeId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("UnitId");

                    b.ToTable("MATERIALS", (string)null);
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Materials.MaterialPurchaseOrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId", "OrderDate");

                    b.ToTable("MATERIAL_PURCHASE_ORDERS", (string)null);
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Materials.MaterialPurchaseOrderItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid");

                    b.Property<string>("MaterialName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Qty")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("UnitCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("MATERIAL_PURCHASE_ITEMS", (string)null);
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Materials.MaterialSupplierEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("MinOrderQty")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("SupplierId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SupplierId");

                    b.HasIndex("MaterialId", "SupplierId")
                        .IsUnique();

                    b.ToTable("MATERIAL_SUPPLIERS", (string)null);
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Materials.MaterialTypeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MATERIAL_TYPES", (string)null);
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Materials.SupplierEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("SUPPLIERS", (string)null);
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Materials.UnitEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("UNITS", (string)null);
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Orders.SalesOrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("RequiredByDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.ToTable("SALES_ORDERS", (string)null);
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Orders.SalesOrderItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("QtyAllocated")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("QtyOrdered")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("QtyShipped")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("SalesOrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal?>("UnitPrice")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SalesOrderId");

                    b.ToTable("SALES_ORDER_ITEMS", (string)null);
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Orders.ShipmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SalesOrderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ShipmentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("SalesOrderId");

                    b.ToTable("SHIPMENTS", (string)null);
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Orders.ShipmentItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Qty")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("SalesOrderItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShipmentId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SalesOrderItemId");

                    b.HasIndex("ShipmentId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("SHIPMENT_ITEMS", (string)null);
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Orders.ShipmentReturnEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Reason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("ReturnDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SalesOrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ShipmentId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("SalesOrderId");

                    b.HasIndex("ShipmentId");

                    b.ToTable("SHIPMENT_RETURNS", (string)null);
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Orders.ShipmentReturnItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Condition")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("Qty")
                        .HasColumnType("integer");

                    b.Property<Guid>("SalesOrderItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ShipmentItemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ShipmentReturnId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WarehouseId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("SalesOrderItemId");

                    b.HasIndex("ShipmentItemId");

                    b.HasIndex("ShipmentReturnId");

                    b.HasIndex("WarehouseId");

                    b.ToTable("SHIPMENT_RETURN_ITEMS", (string)null);
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Organization.DepartmentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("DEPARTMENTS", (string)null);
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Organization.EmployeeEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Grade")
                        .HasColumnType("integer");

                    b.Property<DateTime>("HiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("PositionId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("PremiumPercent")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("RatePerNormHour")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.ToTable("EMPLOYEES", (string)null);
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Organization.PositionEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("BaseNormPerHour")
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal?>("BaseRatePerNormHour")
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("CanCut")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanHandleMaterials")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanPackage")
                        .HasColumnType("boolean");

                    b.Property<bool>("CanSew")
                        .HasColumnType("boolean");

                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal?>("DefaultPremiumPercent")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("DepartmentId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("POSITIONS", (string)null);
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Parties.ContactEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ContactType")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.HasKey("Id");

                    b.ToTable("CONTACTS", (string)null);
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Parties.ContactLinkEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<int>("OwnerType")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ContactId");

                    b.HasIndex("OwnerId");

                    b.ToTable("CONTACT_LINKS", (string)null);
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Parties.CustomerEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("CUSTOMERS", (string)null);
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Production.CuttingOperationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("OperationDate")
                        .HasColumnType("date");

                    b.Property<Guid>("ProductionOrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("QtyCut")
                        .HasColumnType("integer");

                    b.Property<int>("QtyPlanned")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ProductionOrderId");

                    b.ToTable("CUTTING_OPERATIONS", (string)null);
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Production.PackagingOperationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("OperationDate")
                        .HasColumnType("date");

                    b.Property<Guid>("ProductionOrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("QtyPacked")
                        .HasColumnType("integer");

                    b.Property<int>("QtyPlanned")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ProductionOrderId");

                    b.ToTable("PACKAGING_OPERATIONS", (string)null);
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Production.ProductionOrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ProductionOrderNumber")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("QtyCut")
                        .HasColumnType("integer");

                    b.Property<int>("QtyFinished")
                        .HasColumnType("integer");

                    b.Property<int>("QtyPacked")
                        .HasColumnType("integer");

                    b.Property<int>("QtyPlanned")
                        .HasColumnType("integer");

                    b.Property<int>("QtySewn")
                        .HasColumnType("integer");

                    b.Property<Guid>("SalesOrderItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ProductionOrderNumber")
                        .IsUnique();

                    b.HasIndex("SalesOrderItemId");

                    b.ToTable("PRODUCTION_ORDERS", (string)null);
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Production.SewingOperationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("HoursWorked")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateOnly>("OperationDate")
                        .HasColumnType("date");

                    b.Property<Guid>("ProductionOrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("QtyPlanned")
                        .HasColumnType("integer");

                    b.Property<int>("QtySewn")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ProductionOrderId");

                    b.ToTable("SEWING_OPERATIONS", (string)null);
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Products.ProductDepartmentCostEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CutCostPerUnit")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ExpensesPerUnit")
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PackCostPerUnit")
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("SewingCostPerUnit")
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("ProductId", "DepartmentId")
                        .IsUnique();

                    b.ToTable("PRODUCT_DEPARTMENT_COSTS", (string)null);
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Products.ProductEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("PayrollRuleId")
                        .HasColumnType("uuid");

                    b.Property<int?>("PlanPerHour")
                        .HasColumnType("integer");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PayrollRuleId");

                    b.HasIndex("Sku")
                        .IsUnique();

                    b.ToTable("PRODUCTS", (string)null);
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Products.ProductImageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("PRODUCT_IMAGES", (string)null);
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Products.ProductMaterialEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("QtyPerUnit")
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("MaterialId");

                    b.HasIndex("ProductId", "MaterialId")
                        .IsUnique();

                    b.ToTable("PRODUCT_MATERIALS", (string)null);
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Security.RoleEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ROLES", (string)null);
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Security.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("USERS", (string)null);
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Finance.CashAdvanceEntity", b =>
                {
                    b.HasOne("MyFactory.Domain.Entities.Organization.EmployeeEntity", "Employee")
                        .WithMany("CashAdvances")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Finance.PayrollAccrualEntity", b =>
                {
                    b.HasOne("MyFactory.Domain.Entities.Organization.EmployeeEntity", "Employee")
                        .WithMany("PayrollAccruals")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Finance.PayrollPaymentEntity", b =>
                {
                    b.HasOne("MyFactory.Domain.Entities.Organization.EmployeeEntity", "Employee")
                        .WithMany("PayrollPayments")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Finance.TimesheetEntity", b =>
                {
                    b.HasOne("MyFactory.Domain.Entities.Organization.DepartmentEntity", "Department")
                        .WithMany("Timesheets")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyFactory.Domain.Entities.Organization.EmployeeEntity", "Employee")
                        .WithMany("Timesheets")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Inventory.FinishedGoodsEntity", b =>
                {
                    b.HasOne("MyFactory.Domain.Entities.Products.ProductEntity", "Product")
                        .WithMany("FinishedGoods")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyFactory.Domain.Entities.Production.ProductionOrderEntity", "ProductionOrder")
                        .WithMany("FinishedGoods")
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyFactory.Domain.Entities.Inventory.WarehouseEntity", "Warehouse")
                        .WithMany("FinishedGoods")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("ProductionOrder");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Inventory.FinishedGoodsMovementEntity", b =>
                {
                    b.HasOne("MyFactory.Domain.Entities.Security.UserEntity", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("MyFactory.Domain.Entities.Inventory.WarehouseEntity", "FromWarehouse")
                        .WithMany("FinishedGoodsMovementsFrom")
                        .HasForeignKey("FromWarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyFactory.Domain.Entities.Inventory.WarehouseEntity", "ToWarehouse")
                        .WithMany("FinishedGoodsMovementsTo")
                        .HasForeignKey("ToWarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("FromWarehouse");

                    b.Navigation("ToWarehouse");
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Inventory.FinishedGoodsMovementItemEntity", b =>
                {
                    b.HasOne("MyFactory.Domain.Entities.Inventory.FinishedGoodsMovementEntity", "Movement")
                        .WithMany("FinishedGoodsMovementItems")
                        .HasForeignKey("MovementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyFactory.Domain.Entities.Products.ProductEntity", "Product")
                        .WithMany("FinishedGoodsMovementItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movement");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Inventory.FinishedGoodsStockEntity", b =>
                {
                    b.HasOne("MyFactory.Domain.Entities.Products.ProductEntity", "Product")
                        .WithMany("FinishedGoodsStocks")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyFactory.Domain.Entities.Inventory.WarehouseEntity", "Warehouse")
                        .WithMany("FinishedGoodsStocks")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Inventory.InventoryMovementEntity", b =>
                {
                    b.HasOne("MyFactory.Domain.Entities.Security.UserEntity", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId");

                    b.HasOne("MyFactory.Domain.Entities.Inventory.WarehouseEntity", "FromWarehouse")
                        .WithMany("InventoryMovementsFrom")
                        .HasForeignKey("FromWarehouseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MyFactory.Domain.Entities.Production.ProductionOrderEntity", "ProductionOrder")
                        .WithMany("InventoryMovements")
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MyFactory.Domain.Entities.Organization.DepartmentEntity", "ToDepartment")
                        .WithMany("InventoryMovements")
                        .HasForeignKey("ToDepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("MyFactory.Domain.Entities.Inventory.WarehouseEntity", "ToWarehouse")
                        .WithMany("InventoryMovementsTo")
                        .HasForeignKey("ToWarehouseId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CreatedByUser");

                    b.Navigation("FromWarehouse");

                    b.Navigation("ProductionOrder");

                    b.Navigation("ToDepartment");

                    b.Navigation("ToWarehouse");
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Inventory.InventoryMovementItemEntity", b =>
                {
                    b.HasOne("MyFactory.Domain.Entities.Materials.MaterialEntity", "Material")
                        .WithMany("InventoryMovementItems")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyFactory.Domain.Entities.Inventory.InventoryMovementEntity", "Movement")
                        .WithMany("InventoryMovementItems")
                        .HasForeignKey("MovementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Movement");
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Inventory.WarehouseMaterialEntity", b =>
                {
                    b.HasOne("MyFactory.Domain.Entities.Materials.MaterialEntity", "Material")
                        .WithMany("WarehouseMaterials")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyFactory.Domain.Entities.Inventory.WarehouseEntity", "Warehouse")
                        .WithMany("WarehouseMaterials")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Inventory.WarehouseProductEntity", b =>
                {
                    b.HasOne("MyFactory.Domain.Entities.Products.ProductEntity", "Product")
                        .WithMany("WarehouseProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyFactory.Domain.Entities.Inventory.WarehouseEntity", "Warehouse")
                        .WithMany("WarehouseProducts")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Materials.MaterialEntity", b =>
                {
                    b.HasOne("MyFactory.Domain.Entities.Materials.MaterialTypeEntity", "MaterialType")
                        .WithMany("Materials")
                        .HasForeignKey("MaterialTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyFactory.Domain.Entities.Materials.UnitEntity", "Unit")
                        .WithMany("Materials")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaterialType");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Materials.MaterialPurchaseOrderEntity", b =>
                {
                    b.HasOne("MyFactory.Domain.Entities.Materials.SupplierEntity", "Supplier")
                        .WithMany("MaterialPurchaseOrders")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Materials.MaterialPurchaseOrderItemEntity", b =>
                {
                    b.HasOne("MyFactory.Domain.Entities.Materials.MaterialEntity", "Material")
                        .WithMany("MaterialPurchaseOrderItems")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyFactory.Domain.Entities.Materials.MaterialPurchaseOrderEntity", "MaterialPurchaseOrder")
                        .WithMany("MaterialPurchaseItems")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("MaterialPurchaseOrder");
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Materials.MaterialSupplierEntity", b =>
                {
                    b.HasOne("MyFactory.Domain.Entities.Materials.MaterialEntity", "Material")
                        .WithMany("MaterialSuppliers")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyFactory.Domain.Entities.Materials.SupplierEntity", "Supplier")
                        .WithMany("MaterialSuppliers")
                        .HasForeignKey("SupplierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Supplier");
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Orders.SalesOrderEntity", b =>
                {
                    b.HasOne("MyFactory.Domain.Entities.Parties.CustomerEntity", "Customer")
                        .WithMany("SalesOrders")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Orders.SalesOrderItemEntity", b =>
                {
                    b.HasOne("MyFactory.Domain.Entities.Orders.SalesOrderEntity", "SalesOrder")
                        .WithMany("SalesOrderItems")
                        .HasForeignKey("SalesOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SalesOrder");
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Orders.ShipmentEntity", b =>
                {
                    b.HasOne("MyFactory.Domain.Entities.Parties.CustomerEntity", "Customer")
                        .WithMany("Shipments")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyFactory.Domain.Entities.Orders.SalesOrderEntity", "SalesOrder")
                        .WithMany("Shipments")
                        .HasForeignKey("SalesOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("SalesOrder");
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Orders.ShipmentItemEntity", b =>
                {
                    b.HasOne("MyFactory.Domain.Entities.Products.ProductEntity", "Product")
                        .WithMany("ShipmentItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyFactory.Domain.Entities.Orders.SalesOrderItemEntity", "SalesOrderItem")
                        .WithMany("ShipmentItems")
                        .HasForeignKey("SalesOrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyFactory.Domain.Entities.Orders.ShipmentEntity", "Shipment")
                        .WithMany("ShipmentItems")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyFactory.Domain.Entities.Inventory.WarehouseEntity", "Warehouse")
                        .WithMany("ShipmentItems")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("SalesOrderItem");

                    b.Navigation("Shipment");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Orders.ShipmentReturnEntity", b =>
                {
                    b.HasOne("MyFactory.Domain.Entities.Parties.CustomerEntity", "Customer")
                        .WithMany("ShipmentReturns")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyFactory.Domain.Entities.Orders.SalesOrderEntity", "SalesOrder")
                        .WithMany("ShipmentReturns")
                        .HasForeignKey("SalesOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyFactory.Domain.Entities.Orders.ShipmentEntity", "Shipment")
                        .WithMany("ShipmentReturns")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Customer");

                    b.Navigation("SalesOrder");

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Orders.ShipmentReturnItemEntity", b =>
                {
                    b.HasOne("MyFactory.Domain.Entities.Products.ProductEntity", "Product")
                        .WithMany("ShipmentReturnItems")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyFactory.Domain.Entities.Orders.SalesOrderItemEntity", "SalesOrderItem")
                        .WithMany("ShipmentReturnItems")
                        .HasForeignKey("SalesOrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyFactory.Domain.Entities.Orders.ShipmentItemEntity", "ShipmentItem")
                        .WithMany("ShipmentReturnItems")
                        .HasForeignKey("ShipmentItemId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("MyFactory.Domain.Entities.Orders.ShipmentReturnEntity", "ShipmentReturn")
                        .WithMany("ShipmentReturnItems")
                        .HasForeignKey("ShipmentReturnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyFactory.Domain.Entities.Inventory.WarehouseEntity", "Warehouse")
                        .WithMany("ShipmentReturnItems")
                        .HasForeignKey("WarehouseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("SalesOrderItem");

                    b.Navigation("ShipmentItem");

                    b.Navigation("ShipmentReturn");

                    b.Navigation("Warehouse");
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Organization.EmployeeEntity", b =>
                {
                    b.HasOne("MyFactory.Domain.Entities.Organization.PositionEntity", "Position")
                        .WithMany("Employees")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Position");
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Organization.PositionEntity", b =>
                {
                    b.HasOne("MyFactory.Domain.Entities.Organization.DepartmentEntity", "Department")
                        .WithMany("Positions")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Parties.ContactLinkEntity", b =>
                {
                    b.HasOne("MyFactory.Domain.Entities.Parties.ContactEntity", null)
                        .WithMany("ContactLinks")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyFactory.Domain.Entities.Organization.EmployeeEntity", null)
                        .WithMany("ContactLinks")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyFactory.Domain.Entities.Parties.CustomerEntity", null)
                        .WithMany("ContactLinks")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyFactory.Domain.Entities.Security.UserEntity", null)
                        .WithMany("ContactLinks")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Production.CuttingOperationEntity", b =>
                {
                    b.HasOne("MyFactory.Domain.Entities.Organization.EmployeeEntity", "Employee")
                        .WithMany("CuttingOperations")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyFactory.Domain.Entities.Production.ProductionOrderEntity", "ProductionOrder")
                        .WithMany("CuttingOperations")
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("ProductionOrder");
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Production.PackagingOperationEntity", b =>
                {
                    b.HasOne("MyFactory.Domain.Entities.Organization.EmployeeEntity", "Employee")
                        .WithMany("PackagingOperations")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyFactory.Domain.Entities.Production.ProductionOrderEntity", "ProductionOrder")
                        .WithMany("PackagingOperations")
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("ProductionOrder");
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Production.ProductionOrderEntity", b =>
                {
                    b.HasOne("MyFactory.Domain.Entities.Organization.DepartmentEntity", "Department")
                        .WithMany("ProductionOrders")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyFactory.Domain.Entities.Orders.SalesOrderItemEntity", "SalesOrderItem")
                        .WithMany("ProductionOrders")
                        .HasForeignKey("SalesOrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("SalesOrderItem");
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Production.SewingOperationEntity", b =>
                {
                    b.HasOne("MyFactory.Domain.Entities.Organization.EmployeeEntity", "Employee")
                        .WithMany("SewingOperations")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyFactory.Domain.Entities.Production.ProductionOrderEntity", "ProductionOrder")
                        .WithMany("SewingOperations")
                        .HasForeignKey("ProductionOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("ProductionOrder");
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Products.ProductDepartmentCostEntity", b =>
                {
                    b.HasOne("MyFactory.Domain.Entities.Organization.DepartmentEntity", "Department")
                        .WithMany("ProductDepartmentCosts")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyFactory.Domain.Entities.Products.ProductEntity", "Product")
                        .WithMany("ProductDepartmentCosts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Products.ProductEntity", b =>
                {
                    b.HasOne("MyFactory.Domain.Entities.Finance.PayrollRuleEntity", null)
                        .WithMany("Products")
                        .HasForeignKey("PayrollRuleId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Products.ProductImageEntity", b =>
                {
                    b.HasOne("MyFactory.Domain.Entities.Products.ProductEntity", "Product")
                        .WithMany("ProductImages")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Products.ProductMaterialEntity", b =>
                {
                    b.HasOne("MyFactory.Domain.Entities.Materials.MaterialEntity", "Material")
                        .WithMany("ProductMaterials")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyFactory.Domain.Entities.Products.ProductEntity", "Product")
                        .WithMany("ProductMaterials")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Material");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Finance.PayrollRuleEntity", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Inventory.FinishedGoodsMovementEntity", b =>
                {
                    b.Navigation("FinishedGoodsMovementItems");
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Inventory.InventoryMovementEntity", b =>
                {
                    b.Navigation("InventoryMovementItems");
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Inventory.WarehouseEntity", b =>
                {
                    b.Navigation("FinishedGoods");

                    b.Navigation("FinishedGoodsMovementsFrom");

                    b.Navigation("FinishedGoodsMovementsTo");

                    b.Navigation("FinishedGoodsStocks");

                    b.Navigation("InventoryMovementsFrom");

                    b.Navigation("InventoryMovementsTo");

                    b.Navigation("ShipmentItems");

                    b.Navigation("ShipmentReturnItems");

                    b.Navigation("WarehouseMaterials");

                    b.Navigation("WarehouseProducts");
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Materials.MaterialEntity", b =>
                {
                    b.Navigation("InventoryMovementItems");

                    b.Navigation("MaterialPurchaseOrderItems");

                    b.Navigation("MaterialSuppliers");

                    b.Navigation("ProductMaterials");

                    b.Navigation("WarehouseMaterials");
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Materials.MaterialPurchaseOrderEntity", b =>
                {
                    b.Navigation("MaterialPurchaseItems");
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Materials.MaterialTypeEntity", b =>
                {
                    b.Navigation("Materials");
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Materials.SupplierEntity", b =>
                {
                    b.Navigation("MaterialPurchaseOrders");

                    b.Navigation("MaterialSuppliers");
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Materials.UnitEntity", b =>
                {
                    b.Navigation("Materials");
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Orders.SalesOrderEntity", b =>
                {
                    b.Navigation("SalesOrderItems");

                    b.Navigation("ShipmentReturns");

                    b.Navigation("Shipments");
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Orders.SalesOrderItemEntity", b =>
                {
                    b.Navigation("ProductionOrders");

                    b.Navigation("ShipmentItems");

                    b.Navigation("ShipmentReturnItems");
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Orders.ShipmentEntity", b =>
                {
                    b.Navigation("ShipmentItems");

                    b.Navigation("ShipmentReturns");
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Orders.ShipmentItemEntity", b =>
                {
                    b.Navigation("ShipmentReturnItems");
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Orders.ShipmentReturnEntity", b =>
                {
                    b.Navigation("ShipmentReturnItems");
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Organization.DepartmentEntity", b =>
                {
                    b.Navigation("InventoryMovements");

                    b.Navigation("Positions");

                    b.Navigation("ProductDepartmentCosts");

                    b.Navigation("ProductionOrders");

                    b.Navigation("Timesheets");
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Organization.EmployeeEntity", b =>
                {
                    b.Navigation("CashAdvances");

                    b.Navigation("ContactLinks");

                    b.Navigation("CuttingOperations");

                    b.Navigation("PackagingOperations");

                    b.Navigation("PayrollAccruals");

                    b.Navigation("PayrollPayments");

                    b.Navigation("SewingOperations");

                    b.Navigation("Timesheets");
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Organization.PositionEntity", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Parties.ContactEntity", b =>
                {
                    b.Navigation("ContactLinks");
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Parties.CustomerEntity", b =>
                {
                    b.Navigation("ContactLinks");

                    b.Navigation("SalesOrders");

                    b.Navigation("ShipmentReturns");

                    b.Navigation("Shipments");
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Production.ProductionOrderEntity", b =>
                {
                    b.Navigation("CuttingOperations");

                    b.Navigation("FinishedGoods");

                    b.Navigation("InventoryMovements");

                    b.Navigation("PackagingOperations");

                    b.Navigation("SewingOperations");
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Products.ProductEntity", b =>
                {
                    b.Navigation("FinishedGoods");

                    b.Navigation("FinishedGoodsMovementItems");

                    b.Navigation("FinishedGoodsStocks");

                    b.Navigation("ProductDepartmentCosts");

                    b.Navigation("ProductImages");

                    b.Navigation("ProductMaterials");

                    b.Navigation("ShipmentItems");

                    b.Navigation("ShipmentReturnItems");

                    b.Navigation("WarehouseProducts");
                });

            modelBuilder.Entity("MyFactory.Domain.Entities.Security.UserEntity", b =>
                {
                    b.Navigation("ContactLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
